services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=projeto
      - POSTGRES_DB=projeto

  backend:
    build: .
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=projeto
      - DB_DATABASE=projeto
    ports:
      - '80:3000'
    depends_on:
      - db
