### Auth ###

POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "LuanNn",
  "email": "20231bsifsa0005@ifba.edu.br",
  "password": "123456"
}

###

POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "12345678"
}

###

POST http://localhost:3000/auth/resendEmail HTTP/1.1
Content-Type: application/json

{
  "email": "20231bsifsa0005@ifba.edu.br"
}

###

GET http://localhost:3000/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4NjcxNTMwLCJleHAiOjE3NTg4NDQzMzB9.SnmpJJoBnw8ckvL9KPD34yJYzBFV2P_ZfmxomTZMbw0

###

GET http://localhost:3000/auth/readers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzYzMjU3NywiZXhwIjoxNzU3ODA1Mzc3fQ.bJInUDHTI0wN8diTTIGZS_0Y_DyBSbtnGqgQpDrQEMU

###

GET http://localhost:3000/auth/readers/Luan HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzYzMjU3NywiZXhwIjoxNzU3ODA1Mzc3fQ.bJInUDHTI0wN8diTTIGZS_0Y_DyBSbtnGqgQpDrQEMU

###

GET http://localhost:3000/auth/writers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1NzYzMjU3NywiZXhwIjoxNzU3ODA1Mzc3fQ.bJInUDHTI0wN8diTTIGZS_0Y_DyBSbtnGqgQpDrQEMU


###

PATCH http://localhost:3000/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU2NTcxMzM4LCJleHAiOjE3NTY3NDQxMzh9.1_Je9pi2n_F52RiqU839iMjhmr_-eHUZDxHjKscJGXw
Content-Type: application/json

{
  "name": "Luannn"
}

###

DELETE http://localhost:3000/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidGVzdDJAYXBlcmlvbC5jb20iLCJyb2xlIjoiTGVpdG9yIiwiaWF0IjoxNzU2NDIyMDA2LCJleHAiOjE3NTY1OTQ4MDZ9.CTL0fLXFjuPdaTc5SSugXPt30NYBYc08AiB1r48hdbY

### Category ###

POST http://localhost:3000/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4NDI0MjU3LCJleHAiOjE3NTg1OTcwNTd9.62VZ6dz5teMu2JPnEAoXwdGZl-B_wCprfI3zoLWgLWA
Content-Type: application/json

{
  "name": "Entretenimento"
}

###

GET http://localhost:3000/category HTTP/1.1

###

GET http://localhost:3000/category/2 HTTP/1.1

###

PATCH http://localhost:3000/category/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU2NTE3MDkxLCJleHAiOjE3NTY2ODk4OTF9.z5_pR9T0_D_UW306vrwAruGuidNaL9ziXFPptX8AIxc
Content-Type: application/json

{
  "name": "Esporte"
}

###

DELETE http://localhost:3000/category/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU2NTE3MDkxLCJleHAiOjE3NTY2ODk4OTF9.z5_pR9T0_D_UW306vrwAruGuidNaL9ziXFPptX8AIxc

### Articles ###

POST http://localhost:3000/article HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4NDIyOTAzLCJleHAiOjE3NTg1OTU3MDN9.FuZj4BwN8CNMxCAky4cE92jqGQFFcISiUeCHTP0GIR0
Content-Type: multipart/form-data; boundary=separation

--separation
Content-Disposition: form-data; name="image"; filename="article.jpg"
Content-Type: image/jpeg

< C/home/luan/Documentos/GitHub/PW/PW/11 - Flutuando elementos/elefante.jpg

--separation
Content-Disposition: form-data; name="title"

Title of my article 15
--separation
Content-Disposition: form-data; name="subtitle"

Subtitle of my article 3
--separation
Content-Disposition: form-data; name="text"

Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque inventore pariatur, velit perferendis exercitationem itaque eius alias nisi maxime sequi facilis consectetur minima dolores dolorem quos, reiciendis iusto ea aspernatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate autem vitae consequatur sunt maxime soluta earum nam, culpa rem nostrum veritatis quod ipsa neque unde dolorem quidem doloremque libero itaque.
--separation
Content-Disposition: form-data; name="categoryId"

3
--separation
Content-Disposition: form-data; name="categoryId"

1
--separation--

###

GET http://localhost:3000/article?size=10&page=0 HTTP/1.1

###

GET http://localhost:3000/article/categories HTTP/1.1
Content-Type: application/json

{
  "categoriesId": [1, 2]
}

###

GET http://localhost:3000/article/latest?size=3&page=0 HTTP/1.1

###

GET http://localhost:3000/article/most-viewed?size=3&page=0 HTTP/1.1

###

GET http://localhost:3000/article/mine HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4NzUyNDkyLCJleHAiOjE3NTg5MjUyOTJ9.w8LJ9zLHO8II7Pd98XivUkzhNz9L0LIKBy1f94EJ2sg

###

GET http://localhost:3000/article/1 HTTP/1.1

###

PATCH http://localhost:3000/article/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU2NTE3MDkxLCJleHAiOjE3NTY2ODk4OTF9.z5_pR9T0_D_UW306vrwAruGuidNaL9ziXFPptX8AIxc
Content-Type: multipart/form-data; boundary=separation

#--separation
#Content-Disposition: form-data; name="image"; filename="article.jpg"
#Content-Type: image/jpeg
#
#< C:\Users\Luan\Documents\GitHub\PW\PW\11 - Flutuando elementos\elefante.jpg

--separation
Content-Disposition: form-data; name="title"

Title of my article 3
--separation
Content-Disposition: form-data; name="subtitle"

Subtitle of my article 3
--separation
Content-Disposition: form-data; name="text"

Oii
--separation
Content-Disposition: form-data; name="categoryId"

2
--separation
Content-Disposition: form-data; name="categoryId"

4
--separation--

###

DELETE http://localhost:3000/article/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU2NTE3MDkxLCJleHAiOjE3NTY2ODk4OTF9.z5_pR9T0_D_UW306vrwAruGuidNaL9ziXFPptX8AIxc

### Roles ###

PATCH http://localhost:3000/role/jornalista/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU2NTE3MDkxLCJleHAiOjE3NTY2ODk4OTF9.z5_pR9T0_D_UW306vrwAruGuidNaL9ziXFPptX8AIxc

###

PATCH http://localhost:3000/role/leitor/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU2NTE3MDkxLCJleHAiOjE3NTY2ODk4OTF9.z5_pR9T0_D_UW306vrwAruGuidNaL9ziXFPptX8AIxc
