### Auth

POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "LuanNn",
  "email": "test2@aperiol.com",
  "password": "123456"
}

###

POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test2@aperiol.com",
  "password": "123456"
}

###

PATCH http://localhost:3000/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidGVzdDJAYXBlcmlvbC5jb20iLCJyb2xlIjoiTGVpdG9yIiwiaWF0IjoxNzU2NDIyMDA2LCJleHAiOjE3NTY1OTQ4MDZ9.CTL0fLXFjuPdaTc5SSugXPt30NYBYc08AiB1r48hdbY
Content-Type: application/json

{
  "name": "Luannn",
  "password": "123456"
}

###

DELETE http://localhost:3000/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidGVzdDJAYXBlcmlvbC5jb20iLCJyb2xlIjoiTGVpdG9yIiwiaWF0IjoxNzU2NDIyMDA2LCJleHAiOjE3NTY1OTQ4MDZ9.CTL0fLXFjuPdaTc5SSugXPt30NYBYc08AiB1r48hdbY

### Role

GET http://localhost:3000/role HTTP/1.1
